# Generated by Django 3.0.3 on 2020-02-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submissions_date',
            new_name='submission_date',
        ),
    ]
